export const LOGIN_TOKEN = 'login/token'
export const LOGIN_NAME = 'login/name'
export const LOGIN_PASSWORD = 'login/password'
export const LOGIN_USERINFO = 'login/userinfo'
export const LOGIN_MENU = 'login/menu'
